services:
  logbookviso:
    container_name: logbookviso
    build: .
    ports:
      - "5000:5000"
    environment:
      LOGBOOK_DB: /data/logbook.sqlite
    volumes:
      # SQLite-Datei vom Host einbinden (nur lesen)
      - ./logbook.sqlite:/opt/docker/logbookviso/data/logbook.sqlite:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    # Externes Netz, das auch SWAG nutzt (ggf. Namen anpassen)
    external: true
    name: proxy
